import type { Metadata } from "next";

import "@/assets/scss/global.scss";
import { fontsClass } from "@/configs";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
    <html lang="en">
        <body className={fontsClass}>{children}</body>
    </html>
);

export default RootLayout;
